## get user
 GET {{URL}}/users/1a2?limit=10&page=1

 ##create users
 POST {{URL}}/users
 Content-Type:application/json
 {
    "name":"waqar",
    "email":"hellp@waqar.com",
    "password":"Waqar@123"

 }
